apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    app: lora-service
  name: lora-full-services
spec:
  type: NodePort
  ports:
    - port: 8080
      name: app-port
    - port: 1700
      targetPort: 1700
      protocol: UDP
      name: gateway-port
    - port: 1883
      targetPort: 1883
      name: mosquitto-port
    - port: 6379
      name: redis-port
  selector:
    app: lora
status:
  loadBalancer: {}
